### ISSUE TITLE
scaling on macos

### ISSUE THREAD

**Issue by nilsbecker** [sanette/bogue#6] opened 2022-01-04 11:58 UTC
in example boguex 29, 

![image](https://user-images.githubusercontent.com/177614/148055425-5b58115a-faa9-4983-bc61-e2bc310617ef.png)

which looks like this on my mac (with a tiny font), clicking on the first button activates it but to activate the AAA button requires clicking somewhere a little above the CCC button. my guess is that resolution scaling works differently on macos with retina displays and xquartz. i've had similar problems in the past. my feeling is that xquartz on retina displays basically does not work properly and is best avoided. is there any way to support bogue apps as native apps? if yes this would be definitely preferable.

**Comment by nilsbecker** [comment] 2022-01-04 11:59
ps BBB and CCC can also be selected by clicking even further down.

**Comment by sanette** [comment] 2022-01-04 12:30
Thanks for reporting! indeed, there is a problem. Bogue relies on SDL for scaling; in principle SDL is responsible for cross-platform (and is indeed very good at this, except for scaling on macs, afaik)

**Comment by sanette** [comment] 2022-01-04 12:32
concerning the tiny font you can try creating a `bogue.conf` file (in the dir where you run `boguex`) with content:
```
## BOGUE version 01-01-2022

SCALE = 2
```
(you can try also 2.5 or 3)

**Comment by sanette** [comment] 2022-01-06 12:44
Could you tell me which version of SDL you have?
(use `sdl2-config --version`, or run any `boguex` example: the SDL version is printed in the console)

**Comment by sanette** [comment] 2022-01-06 13:19
Could you also execute the following lines in an `ocaml` toplevel and post the result?
```ocaml
#thread;;
#require "tsdl";;
open Tsdl.Sdl;;
init (Init.video);;
get_current_video_driver ();;
get_num_video_displays ();;
get_display_dpi 0;;
get_current_display_mode 0;;
let w, r = match create_window_and_renderer ~w:800 ~h:600 Window.(windowed + resizable + opengl + allow_highdpi) with Ok (w,r) -> w,r | Error (`Msg s) -> failwith s;;
render_get_scale r;;
get_window_size w;;
get_window_display_mode w;;
Window.(test (get_window_flags w) allow_highdpi);;
destroy_renderer r;;
destroy_window w;;
```

**Comment by nilsbecker** [comment] 2022-01-10 09:44
hi, sorry for the delay. the sdl version is 2.0.18. 

the snippet above generates the following aggregated output:
```
- : unit Tsdl.Sdl.result = Ok ()
- : string option = Some "cocoa"
- : int Tsdl.Sdl.result = Ok 1
- : (float * float * float) Tsdl.Sdl.result = Ok (216.51, 217, 215)
- : display_mode Tsdl.Sdl.result =
Ok
 {dm_format = <abstr>; dm_w = 2560; dm_h = 1440; dm_refresh_rate = Some 60;
  dm_driverdata = Some <abstr>}
val w : window = <abstr>
val r : renderer = <abstr>
- : float * float = (1, 1)
- : int * int = (800, 600)
- : display_mode Tsdl.Sdl.result =
Ok
 {dm_format = <abstr>; dm_w = 800; dm_h = 600; dm_refresh_rate = Some 60;
  dm_driverdata = Some <abstr>}
- : bool = true
- : unit = ()
- : unit = ()
```

**Comment by sanette** [comment] 2022-01-10 11:30
hum that's weird. Your render_get_scale is (1,1) so I don't understand the scaling issue. I tried on a macos virtual machine yesterday and there was no problem.

By the way there is a bug in SDL 2.0.18 that strongly affects Bogue. The fix in underway (https://github.com/libsdl-org/SDL/commit/dca281e810263f1fbf9420c2988932b7700be1d4) but in the meantime I have uploaded a workaround (https://github.com/sanette/bogue/commit/5ffdb4847773c74dd0270f09667830f0289c3dd3). It should also detect your DPI.

**Comment by sanette** [comment] 2022-01-10 11:32
does it make any difference if you remove the `allow_highdpi` flag?

**Comment by sanette** [comment] 2022-01-10 17:48
Btw the video driver says "cocoa", I suppose it means it does not use Xquartz

**Comment by nilsbecker** [comment] 2022-01-10 18:29
i can retry tomorrow on that machine. it's a 27'' imac so the native screen resolution is 5120 x 2880. that only half is reported seems to be the way it is on retina. this kind of issue is probably hard to debug on a vm.

**Comment by sanette** [comment] 2022-01-11 08:50
> this kind of issue is probably hard to debug on a vm.

of course, you're right. Sorry if I'm over-using you!
ideally I would like to test with/without the HIGH-DPI and the OPENGL flags. And check `Sdl.gl_get_drawable_size`.
I'll try to find a physical machine!
The bug is maybe related to this one:
https://github.com/libsdl-org/SDL/issues/1197

**Comment by nilsbecker** [comment] 2022-01-11 09:54
hi, no worries. i can always not answer if it's taking too much time ;). output without `allow_hidpi`:
```
- : unit Tsdl.Sdl.result = Ok ()
- : string option = Some "cocoa"
- : int Tsdl.Sdl.result = Ok 1
- : (float * float * float) Tsdl.Sdl.result = Ok (216.51, 217, 215)
- : display_mode Tsdl.Sdl.result =
Ok
 {dm_format = <abstr>; dm_w = 2560; dm_h = 1440; dm_refresh_rate = Some 60;
  dm_driverdata = Some <abstr>}
val w : window = <abstr>
val r : renderer = <abstr>
- : float * float = (1, 1)
- : int * int = (800, 600)
- : display_mode Tsdl.Sdl.result =
Ok
 {dm_format = <abstr>; dm_w = 800; dm_h = 600; dm_refresh_rate = Some 60;
  dm_driverdata = Some <abstr>}
- : bool = false
- : unit = ()
- : unit = ()
```

about xquartz. in my previous tests i saw that xquartz had launched and appeared as an app icon in the task bar. therefore i assumed xquartz was used. i even tried several times to make sure. 

now i retried again by typing `boguex` with xquartz not running. this time, no xquartz icon! it appears either something has changed with the newest opam version of bogue, or my previous conclusion was wrong. currently, no xquartz.

on `boguex 9` the scaling issue is clearly visible: the button is moving with the mouse but at half the distance to a certain point on the canvas where both do overlap. this point is roughly at x=10% y=25% of the canvas from left, top.

the offset between buttons and clickable areas remains in `boguex 29`

**Comment by nilsbecker** [comment] 2022-01-11 09:59
also as a side note, the sound file for `boguex 36` is not found

**Comment by sanette** [comment] 2022-01-11 10:39
> also as a side note, the sound file for `boguex 36` is not found

yes, one of the samples is copyrighted, I need to change it

Thanks for your time! I'm a bit confused that you get the same screen size 2560,1440 even without allow_highdpi. I've just opened an issue in the SDL forum to try and understand this.

I didn't change the opam package yet. The github version is slightly changed, but I don't see why this should have any effect on using xquartz or not...

**Comment by nilsbecker** [comment] 2022-01-11 12:18
about screen size: i have encountered the same issue before, i think it was in the context of inkscape. retina seems to somehow hide the native resolution from apps iiuc.

**Comment by sanette** [comment] 2022-01-11 21:57
ok I was able to get a retina machine. A quick way to "fix" the problem is to remove the 'allow_highdpi' flag in the file b_draw.ml (line 1105)
However this is not perfect because graphics are a bit blurry, less crisp than they should be.

**Comment by nilsbecker** [comment] 2022-01-12 09:13
ah yes, that is probably the option to render at non-retina resolution. for apps this can also be set on the macos system level. to do that go to /Applications, select one of them, open the info window with command-i and then check the box 'open in low resolution'. this sets a plist entry somewhere i assume. of course it's not desirable to have to do that.

**Comment by sanette** [comment] 2022-01-12 15:49
I have uploaded a new branch (retina) which I think solves this scaling issue, and should have crisps graphics.
It'd be great if you had some time to test it:
```
git clone https://github.com/sanette/bogue.git
cd bogue 
git checkout retina
dune exec examples/example.exe 29 
```

**Comment by sanette** [comment] 2022-01-12 16:16
Here is what I'm getting
<img width="317" alt="Capture d’écran 2022-01-12 à 17 16 18" src="https://user-images.githubusercontent.com/7536536/149178791-d54e30dc-7c1d-48a8-9cb6-c44b34eb855b.png">

**Comment by nilsbecker** [comment] 2022-01-14 09:42
yup, that works perfectly for me too. great work!

**Comment by nilsbecker** [comment] 2022-01-14 09:56
i quickly went through the examples in the retina branch

- ex 9: i noticed an offset between mouse and attached button. not sure if intended
- ex 26: the region slightly changes size on mouse enter/leave. may have to do with the text changing
- ex 27: the scrolling speed when using a trackpad is about twice as fast as standard for macos apps. the UI convention for mac is this: dragging two fingers on the trackpad by a vertical distance x should scroll the text as far as dragging one finger by x moves the cursor
- when clicking with the mouse on the x button to close an example window, but missing it by a little, the mouse is teleported to the top left of the screen (?!) somtimes. difficult to reproduce
- ex 31: scrolling with two-finger drag is choppy and sometimes hangs. scrolling by dragging the slider on the right works fine.
- ex 32: same
- ex 33,34: ditto
- 36 no wav file

**Comment by nilsbecker** [comment] 2022-01-14 10:17
- 43 right checkbox cannot be clicked
-

**Comment by sanette** [comment] 2022-01-14 16:32
many many thanks for the tests!

Some remarks:


> * ex 9: i noticed an offset between mouse and attached button. not sure if intended

This is not specific to macOS. It is due I think in the delay of SDL initialization wrt/ the initial mouse position. This example is really not that interesting...

> 
> * ex 26: the region slightly changes size on mouse enter/leave. may have to do with the text changing

Yes, this is the expected behavior: the region should expand (with animation) on mouse_over
> 
> * ex 27: the scrolling speed when using a trackpad is about twice as fast as standard for macos apps. the UI convention for mac is this: dragging two fingers on the trackpad by a vertical distance x should scroll the text as far as dragging one finger by x moves the cursor
> 

Right, I never understood why touchpad scrolling on MacOS is so slow ;)  I have reproduced in Bogue more or less what I observe in my Linux laptop in other apps like Firefox: scrolling with touchpad is roughly equivalent to scrolling with mouse wheel, and is approx twice as fast as the corresponding cursor motion. But mac users never had a mouse wheel (be default) so I can understand it feels strange for them. Maybe I should decide for an in-between behavior...

> * when clicking with the mouse on the x button to close an example window, but missing it by a little, the mouse is teleported to the top left of the screen (?!) somtimes. difficult to reproduce

Wow! this is weird (and MacOS specific afaict). I indeed have the same problem on the MacBook Pro I borrowed, in fact it's reproducible: each *first* time you click *anywhere* on the window top bar, you get teleported to top left corner! What is weird is that Bogue never touches these kinds of events, and never sets the mouse position...

> 
> * ex 31: scrolling with two-finger drag is choppy and sometimes hangs. scrolling by dragging the slider on the right works fine.
> 
> * ex 32: same
> 
> * ex 33,34: ditto
> 

I have these scrolling problems in linux too; I think they appeared after one of the last updates... Need to investigate.

> * 36 no wav file

I need to fix this

**Comment by sanette** [comment] 2022-01-14 16:35
> * 43 right checkbox cannot be clicked

this is the expected behaviour. The snapshot layout on the right is just a pixel copy of the layout on the left, nothing is active on it (just an image)

However this example did not work for me on the Mac I borrowed. For some reason the snapshot on the right does not show up at all. (it should be spinning and zooming)

**Comment by nilsbecker** [comment] 2022-01-14 22:27
in 43 the snapshot did spin and zoom for me... 
about the teleporting: could this be an upstream sdl bug?
scroll speed: on mac computers you usually have a big trackpad, so the default does make sense imo. it's very easy to get used to; especially with the default scrolling direction. it feels like you are placing your finger on a sheet of paper and sliding it up or down. so i would vote for replicating the standard macos app behavior ;)

**Comment by sanette** [comment] 2022-01-16 08:29
> 36 no wav file

this is now fixed (along with the retina branch) in the new opam version!

**Closed as completed** 2022-02-21 15:57 UTC

**Comment by sanette** [comment] 2022-02-21 16:00
I'm closing this because the original issue is solved. But the touchpad scrolling issue remains. It's better to open another issue for this
