### ISSUE TITLE
unable to install bogue using opam

### ISSUE THREAD

**Issue by RodrigoVillar** [sanette/bogue#4] opened 2021-12-14 03:26 UTC
whenever i try to install bogue using `opam install bogue`, i get the following error message:
```
(base) peru@MacBook-Pro-4 CamlCoin % opam install bogue
[NOTE] It seems you have not updated your repositories for a while. Consider updating them with:
       opam update

The following actions will be performed:
  ∗ install conf-sdl2-image 1        [required by tsdl-image]
  ∗ install tsdl-image      0.3.0    [required by bogue]
  ∗ install bogue           20210917
===== ∗ 3 =====
Do you want to continue? [Y/n] y

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
⬇ retrieved tsdl-image.0.3.0  (cached)
⬇ retrieved bogue.20210917  (cached)
[ERROR] The compilation of conf-sdl2-image.1 failed at "pkg-config SDL2_image".

#=== ERROR while compiling conf-sdl2-image.1 ==================================#
# context     2.1.0 | macos/x86_64 | ocaml-base-compiler.4.12.0 | https://opam.ocaml.org#a77320e3
# path        ~/.opam/caml-coin-switch/.opam-switch/build/conf-sdl2-image.1
# command     ~/.opam/opam-init/hooks/sandbox.sh build pkg-config SDL2_image
# exit-code   1
# env-file    ~/.opam/log/conf-sdl2-image-61409-3bb6cf.env
# output-file ~/.opam/log/conf-sdl2-image-61409-3bb6cf.out



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
┌─ The following actions failed
│ λ build conf-sdl2-image 1
└─ 
╶─ No changes have been performed
```

**Comment by sanette** [comment] 2021-12-14 07:54
The problem is with the package `conf-sdl2-image`
which is supposed to tell `opam` how to install the SDL2_image library on your system.
You can have a look at the output file `~/.opam/log/conf-sdl2-image-61409-3bb6cf.out`
You can also try `opam update; opam upgrade` 
and then `opam install conf-sdl2-image`.
If this still fails, you would have to install SDL2 manually.

**Comment by sanette** [comment] 2021-12-26 22:10
`conf-sdl2-image` was recently updated, could you try again?

**Comment by sanette** [comment] 2022-01-16 21:33
I'm closing this because I think the issue is solved in current version. Feel free to reopen if necessary.

**Closed as completed by sanette** 2022-01-16 21:33 UTC
