### ISSUE TITLE
boguex crashing with "Empty chain has not depth"

### ISSUE THREAD

**Issue by ColMcp** [sanette/bogue#8] opened 2022-01-16 12:08 UTC
I'm using bogue 20220115 / SDL 2.0.20 under macOS Monterey (12.1) on a MacBook Pro.
The boguex example runner is crashing on several of the examples I've run so far. For example:
```
% boguex 4
Loading Bogue 20220115 with config dir /Users/colin/.opam/default/share/bogue/themes/default
2022-01-16 11:56:39.405 boguex[40133:5518170] INFO: Using SDL 2.0.20
4 = rounded box; the whole layout is animated
SDL ERROR: Unknown touch device id -1, cannot reset
Fatal error: exception Invalid_argument("Empty chain has not depth")

```
It usually happens when I click on a checkbox, having already clicked successfully on the other checkbox in the window.
The SDL error message doesn't always appear, but mostly it does.

**Comment by sanette** [comment] 2022-01-16 13:57
mmm. I can't reproduce this.

**Comment by ColMcp** [comment] 2022-01-16 14:02
It's still happening here with the cloned copy of your GitHub repository. Is there anything I can do to help you debug it?
Could it be an SDL2 problem - are you running the same version as me (2.0.20, installed via home-brew today)?

**Comment by sanette** [comment] 2022-01-16 14:10
I'm running a much older version, 2.0.10.
Is this happening with mouse or TouchPad?

**Comment by sanette** [comment] 2022-01-16 14:11
I don't have a Mac for testing right now unfortunately. I'm running linux

**Comment by sanette** [comment] 2022-01-16 14:13
This error (emitted by SDL) is probably key to the problem
`SDL ERROR: Unknown touch device id -1, cannot reset`

**Comment by ColMcp** [comment] 2022-01-16 14:18
I'm using the touchpad. I'll see if I've got a mouse somewhere and try with that.

**Comment by sanette** [comment] 2022-01-16 14:24
could you also try with debug enabled, like this:
`BOGUE_DEBUG=true boguex 4`

**Comment by ColMcp** [comment] 2022-01-16 14:45
Here is the debug output (attached).
I can't find a plug-in mouse, only a Bluetooth one which needs batteries that I don't have!
[bogue.log](https://github.com/sanette/bogue/files/7877156/bogue.log)

**Comment by sanette** [comment] 2022-01-16 17:46
Thanks for the help. The error seems to be related to this SDL maybe-bug:
https://stackoverflow.com/questions/63983054/sdl-geterror-returning-an-undocumented-error-on-macos

**Comment by sanette** [comment] 2022-01-16 18:06
I understand the "empty chain" bug, it's very minor: when a fatal error occurs, Bogue will print out the current state of Layouts, and the bug was in the printing function.

**Comment by sanette** [comment] 2022-01-16 18:32
> I understand the "empty chain" bug, it's very minor: when a fatal error occurs, Bogue will print out the current state of Layouts, and the bug was in the printing function.

This should be fixed in the github version

**Comment by sanette** [comment] 2022-01-16 19:09
Thanks a lot for helping, by the way! If you have some time, could you try with a previous SDL version?
`brew switch sdl2 2.0.18`

**Comment by ColMcp** [comment] 2022-01-17 09:51
Thanks for investigating this. After a bit of messing around I've managed to install SDL2 2.0.18 (the `switch` command is no longer present in `brew`) and I can confirm `boguex 4` now works as expected.

**Comment by sanette** [comment] 2022-01-17 13:38
I'm closing this, assuming the problem came from SDL, but feel free to reopen in case you suspect anything else.

**Closed as completed by sanette** 2022-01-17 13:38 UTC
